# Generated by Django 5.2.5 on 2025-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='tarea',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
